# Generated by Django 5.0.6 on 2024-05-27 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lamp_id', models.CharField(max_length=255)),
                ('brightness', models.IntegerField(blank=True, null=True)),
                ('color_r', models.IntegerField(blank=True, null=True)),
                ('color_g', models.IntegerField(blank=True, null=True)),
                ('color_b', models.IntegerField(blank=True, null=True)),
                ('state', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
